### ISSUE TITLE
SSL/TLS name mismatch

### ISSUE THREAD

**Issue by 56k-modem** [1j01/retrores#1]
In the readme, the "view it here" link pointing to https://retrores.fairuse.org/

```
Certificate Serial: 5218714233543663820411598071248666162

SSL/TLS Status: name mismatch

Expiration Date: 2025-02-14

DN: 
CN=*.netlify.app,O=Netlify\, Inc,L=San Francisco,ST=California,C=US

Issuer DN: 
CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1,O=DigiCert Inc,C=US
```

**Comment by 1j01** [comment]
Looks like the site has been deleted. Actually, looks like my whole account with the hosting provider has been deleted. I might have purposely let it lapse, I don't remember. 
At any rate, the site never amounted to much (you're not really missing out), and I would want to find new hosting if I was revisiting this project.
For now, I've removed references to the site.
